"""Add social media insights to influencer profiles

Revision ID: 8846e3b6e5de
Revises: 25033b6f0239
Create Date: 2025-10-30 04:07:44.807298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8846e3b6e5de'
down_revision: Union[str, None] = '25033b6f0239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_profiles', sa.Column('instagram_insights', sa.JSON(), nullable=True))
    op.add_column('influencer_profiles', sa.Column('tiktok_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencer_profiles', 'tiktok_insights')
    op.drop_column('influencer_profiles', 'instagram_insights')
    # ### end Alembic commands ###
